name: deploy
on:
  push:
    branches: [main,google-push]
    tags: [v*]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: eth-cloud-mb
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=gcr.io/eth-cloud-mb/${{ github.repository }}:latest
          DOCKERFILE_PATH=docker/Dockerfile

          # Build and push the Docker image
          docker build -t $IMAGE_NAME -f $DOCKERFILE_PATH .
          docker push $IMAGE_NAME
